[tox]
envlist = py310
skipsdist = true

[testenv]
deps =
    pytest
    pytest-asyncio
    pytest-cov
    httpx
    aiosqlite
    factory-boy
    Faker
commands =
    pytest --cov=app --cov-report=term